name: Reusable Build and Push to ECR

on:
  workflow_call:
    inputs:
      caller_repo:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ inputs.aws_region }}"

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ inputs.caller_repo }}-${{ github.sha }}
          docker build -t ${{ inputs.ecr_repository }} .

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ inputs.caller_repo }}-${{ github.sha }}
          docker tag ${{ inputs.ecr_repository }}:$IMAGE_TAG public.ecr.aws/y1a8b4n4/${{ inputs.ecr_repository }}:$IMAGE_TAG
          docker push public.ecr.aws/y1a8b4n6/${{ inputs.ecr_repository }}:$IMAGE_TAG

      - name: Print caller repository URL
        run: |
          echo "Caller Repository URL: ${{ inputs.caller_repo }}"
