name: Reusable Build and Push to ECR

on:
  workflow_call:
    inputs:
      caller_repo:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ inputs.caller_repo }}-${{ github.sha }}
          docker build -t ${{ inputs.ecr_repository }}:$IMAGE_TAG .

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ inputs.caller_repo }}-${{ github.sha }}
          docker tag ${{ inputs.ecr_repository }}:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:$IMAGE_TAG

      - name: Print caller repository URL
        run: |
          echo "Caller Repository URL: ${{ inputs.caller_repo }}"
